sudo: required
dist: trusty
language: c
compiler:
  - gcc

env:
  matrix:
    - PG=9.5 LUA=lua-5.3.4
    - PG=9.6 LUA=lua-5.3.4
    - PG=10  LUA=lua-5.3.4
    - PG=10  LUA=LuaJIT-ea7071d
    - PG=11  LUA=lua-5.3.4

addons:
  apt:
    sources:
    - sourceline: "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 11"
      key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo apt-get update
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-${PG:?} postgresql-server-dev-${PG:?}
  - |
    mkdir "$LUA"
    if [[ "$LUA" == lua-* ]]; then
      wget -O- http://www.lua.org/ftp/"$LUA".tar.gz \
        | tar zx --strip-components=1 -C "$LUA"
      make -C "$LUA"/src \
        SYSCFLAGS="-DLUA_USE_LINUX -ULUA_COMPAT_5_2" \
        MYCFLAGS="-fPIC" liblua.a luac
      export LUAC="$LUA/src/luac"
    elif [[ "$LUA" == LuaJIT-* ]]; then
      wget -O- https://github.com/LuaJIT/LuaJIT/archive/"${LUA#LuaJIT-}".tar.gz \
        | tar zx --strip-components=1 -C "$LUA"
      make -C "$LUA"/src \
        XCFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT" \
        CFLAGS="-fPIC -O3" libluajit.a luajit
      export LUAJIT="$LUA/src/luajit"
    fi
    export LUA_INCDIR="$LUA/src"
    mv $LUA/src/liblua*.a ./libcurrent_lua_build.a
    export LUALIB="-L. -lcurrent_lua_build"

before_script:
  - sudo -u postgres createuser -s "$USER"

script:
  - make && sudo make install && time make installcheck

after_script:
  - cat regression.diffs || true
